CREATE TABLE auth_tokens (

id BIGSERIAL PRIMARY KEY,
token VARCHAR(36) NOT NULL,
user_id UUID NOT NULL,
type VARCHAR(50) NOT NULL,
expires_at TIMESTAMP NOT NULL,
used BOOLEAN DEFAULT FALSE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT fk_auth_user FOREIGN KEY (user_id) REFERENCES users(id)
);